# Build DOCX document from LaTeX source
name: PanDocX Build
on: [push]
jobs:
  PanDocX-BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Setup working directory
        uses: actions/checkout@v3
      - run : mkdir output
      - name: Build DOCX through PanDoc
        uses: docker://pandoc/core:2.18
        with:
          args: >- # allows multi-line parsing
            -s main.tex 
            -f latex 
            -t docx 
            -o output/raw_draft.docx 
            --bibliography Bibliografia/Articoli.bib 
            --bibliography Bibliografia/Testi.bib 
            --bibliography Bibliografia/Web.bib 
            --csl ieee.csl --citeproc --toc
      - name: Prepare artifact and upload
        uses: actions/upload-artifact@master
        with:
          name: download
          path: output