# Build PDF document from LaTeX source
name: LaTeXmk Build 
on: [push]
jobs:
  LaTeXmk-BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Setup working directory
        uses: actions/checkout@v3
      - run : mkdir output  
      - name: Build PDF through LaTeXmk
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - run : mv main.pdf output/draft.pdf
      - name: Prepare artifact and clean-up
        uses: actions/upload-artifact@master
        with:
          name: download.pdf
          path: output