name: Build PDF document from LaTeX source
on: [push]
jobs:
  PdfLaTeX_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup working directory
        uses: actions/checkout@v2
      - run : mkdir output  
      - name: Build PDF through LaTeXmk
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - run : mv main.pdf output/draft.pdf
      - name: Prepare artifact and clean-up
        uses: actions/upload-artifact@master
        with:
          name: pdflatex
          path: output